<?php

namespace TeamBundle\Repository;

/**
 * DiplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiplomeRepository extends \Doctrine\ORM\EntityRepository
{
}
